version: '3.9'
services:
  java_react:
    image: openjdk:17-jdk-alpine
    container_name: java_react_container
    ports:
      - "8080:8080"
    volumes:
      - /path/to/java_react/target:/target
    command: ["java", "-jar", "/target/java_react-0.0.1-SNAPSHOT.jar"]
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/mydb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: postgres:14-alpine
    container_name: postgres_db_container
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=mydb

volumes:
  postgres_data: